# Generated by Django 5.0.6 on 2024-06-28 01:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='IIN or BIN must be 12 digits')])),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField()),
            ],
            options={
                'verbose_name': '(Handbook) School',
                'verbose_name_plural': '(Handbook) Schools',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(unique=True)),
            ],
            options={
                'verbose_name': '(Handbook) Region',
                'verbose_name_plural': '(Handbook) Regions',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(max_length=25)),
                ('portNo', models.IntegerField()),
                ('channelID', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.organization')),
            ],
            options={
                'verbose_name': '(Basic) Device',
                'verbose_name_plural': '(Basic) Devices',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.region'),
        ),
    ]
