# Generated by Django 5.0.6 on 2024-06-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='login',
            field=models.CharField(default='sd', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='maxRecordNum',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='maxResults',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(default='sad', max_length=25),
            preserve_default=False,
        ),
    ]
