# Generated by Django 5.0.6 on 2024-07-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
