# Generated by Django 5.0.6 on 2024-07-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_device_login_device_maxrecordnum_device_maxresults_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='channelID',
            new_name='channel_id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='ipAddress',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='maxRecordNum',
            new_name='max_record_num',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='maxResults',
            new_name='max_results',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='portNo',
            new_name='port_no',
        ),
    ]
