# Generated by Django 5.0.6 on 2024-12-31 07:55

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_organization_parent_alter_organization_bin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FIO',
            field=models.CharField(max_length=100, verbose_name='FIO'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
