# Generated by Django 5.0.6 on 2025-02-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_device_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_online',
        ),
    ]
